version: '3.8'

services:
  # --- 1. DATABASE ---
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123! # Mật khẩu DB
    ports:
      - "1433:1433"
    networks:
      - my-network

  # --- 2. BACKEND CỦA BẠN (SERVICE 3) ---
  userservice:
    # Tải image từ Docker Hub (đã test CI/CD)
    image: ducknolife/userservice:latest
    container_name: userservice_container
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # QUAN TRỌNG: Server=db (trỏ đúng tên service database ở trên)
      - "ConnectionStrings__DefaultConnection=Server=db;Database=UserManagementDb;User Id=sa;Password=Password123!;TrustServerCertificate=True;"
      - "Jwt__Key=1234567890qwertyuiopgsdgsdgsdgsdgsdgsdgsdgdsgsdgsdgsdgdsgsdgsdgdsgsdrewwetwetewtwetewtewtwetwetwetewweewrwererwerwerewrwerwerwerwe"
    ports:
      - "5197:8080" # Mở cổng 5197 cho Frontend gọi vào
    networks:
      - my-network

networks:
  my-network:
    driver: bridge